### PR TITLE
Update to 1.0.0-alpha and remove build artifacts from repo

### PR DESCRIPTION
**Pull request by josephglanville**
This removes a bunch of files that are created during the build process and don't need to be committed.
It also updates the example to use rust 1.0.0-alpha, including adding some feature gates to reduce warnings.

### CODE REVIEW

**Comment by steveklabnik** [comment]
I left the artifacts in for reasons I don't quite recall right this moment... i'll check this out soon, i'm about to board 24 hours worth of flights!

**Comment by steveklabnik** [comment]
(and thank you)

**Comment by josephglanville** [comment]
From the .gitignore it looks like you intended to not commit the auto-generated Makefile that extconf spits out at least. Would be curious to hear why you committed the object files if you can remember though.

Fly safe, hope you enjoyed Australia. :)

**Comment by badboy** [comment]
> @badboy_ so in this case I am only because then you can try it without having Rust installed. if it were a real project, no

https://twitter.com/steveklabnik/status/522744646674706432

**Comment by josephglanville** [comment]
Ahh makes sense. Will leave the object files alone then. :)

**Comment by steveklabnik** [comment]
Ahh yes, that was it

**Comment by steveklabnik** [comment]
thanks for this!

**Pull request merged**
